---
- name: Final cluster cleanup pass
  when: ACTION == "provision"
  ansible.builtin.include_role:
    name: deliver_openshift_ops_day.automation.ocp4_workload_cluster_cleanup

- name: Skip cleanup on destroy
  when: ACTION == "destroy"
  debug:
    msg: "Skipping cluster cleanup on destroy"
