---
- name: Set _ocp4_workload_openshift_gitops_domain
  ansible.builtin.set_fact:
    _ocp4_workload_openshift_gitops_domain: "{{ openshift_cluster_ingress_domain }}"

- name: Install OpenShift GitOps operator
  ansible.builtin.include_role:
    name: install_operator
  vars:
    install_operator_action: install
    install_operator_name: openshift-gitops-operator
    install_operator_namespace: openshift-gitops-operator
    install_operator_channel: "{{ ocp4_workload_openshift_gitops_channel }}"
    install_operator_catalog: redhat-operators
    install_operator_automatic_install_plan_approval: "{{ ocp4_workload_openshift_gitops_automatic_install_plan_approval | default(true) }}"
    install_operator_starting_csv: "{{ ocp4_workload_openshift_gitops_starting_csv }}"
    install_operator_catalogsource_setup: "{{ ocp4_workload_openshift_gitops_use_catalog_snapshot | default(false) }}"
    install_operator_catalogsource_name: "{{ ocp4_workload_openshift_gitops_catalogsource_name | default('') }}"
    install_operator_catalogsource_namespace: "{{ ocp4_workload_openshift_gitops_catalogsource_namespace | default('openshift-gitops-operator') }}"
    install_operator_catalogsource_image: "{{ ocp4_workload_openshift_gitops_catalog_snapshot_image | default('') }}"
    install_operator_catalogsource_image_tag: "{{ ocp4_workload_openshift_gitops_catalog_snapshot_image_tag | default('') }}"
    install_operator_subscription_config: "{{ ocp4_workload_openshift_gitops_subscription_config }}"

- name: Grant cluster-admin permissions to Gitops Service account
  when: ocp4_workload_openshift_gitops_setup_cluster_admin | bool
  kubernetes.core.k8s:
    state: present
    src: clusterrolebinding.yaml

- name: Wait until openshift-gitops ArgoCD instance has been created
  kubernetes.core.k8s_info:
    api_version: argoproj.io/v1beta1
    kind: ArgoCD
    name: openshift-gitops
    namespace: openshift-gitops
  register: r_openshift_gitops
  retries: 16
  delay: 60
  until:
  - r_openshift_gitops is defined
  - r_openshift_gitops.resources is defined
  - r_openshift_gitops.resources | length == 1

- name: Create the kustomize-envvar plugin configmap
  when: ocp4_workload_openshift_gitops_kustomize_plugin | bool
  kubernetes.core.k8s:
    state: present
    src: cm-kustomize-envvar.yaml

- name: Update the openshift-gitops ArgoCD instance
  kubernetes.core.k8s:
    state: patched
    template: openshift-gitops.yaml.j2

- name: Create per-user AppProjects
  when: ocp4_workload_openshift_gitops_per_user_access | bool
  kubernetes.core.k8s:
    state: present
    template: appproject-user.yaml.j2
  loop: "{{ range(1, ocp4_workload_openshift_gitops_user_count | int + 1) | list }}"
  loop_control:
    loop_var: _user_num
  vars:
    _username: "{{ ocp4_workload_openshift_gitops_user_base }}{{ _user_num }}"

- name: Attempt to install the ArgoCD CLI to the bastion
  when: ocp4_workload_openshift_gitops_install_cli_tools | bool
  block:
  - name: Get the OpenShift Gitops ArgoCD server route
    kubernetes.core.k8s_info:
      api_version: route.openshift.io/v1
      kind: Route
      name: openshift-gitops-server
      namespace: openshift-gitops
    register: r_openshift_gitops_server_route

  - name: Try to install the ArgoCD CLI
    become: true
    delegate_to: "{{ groups['bastions'][0] }}"
    ansible.builtin.get_url:
      url: >-
        https://{{ r_openshift_gitops_server_route.resources[0].spec.host }}/download/argocd-linux-amd64
      dest: /usr/bin/argocd
      validate_certs: false
      owner: root
      group: root
      mode: ug=rwx,o=rx
    retries: 10
    delay: 5
    ignore_errors: true

# yamllint disable rule:line-length
- name: Save AgnosticD User data
  block:
  - name: Print project information
    agnosticd.core.agnosticd_user_info:
      msg: "OpenShift GitOps ArgoCD: https://openshift-gitops-server-openshift-gitops.{{ _ocp4_workload_openshift_gitops_domain }}"
      data:
        openshift_gitops_server: "https://openshift-gitops-server-openshift-gitops.{{ _ocp4_workload_openshift_gitops_domain }}"
# yamllint enable rule:line-length
